import {env} from 'cloudflare:workers';
const db=()=>{if(!env.DB)throw Error('DB unavailable');return env.DB};
const s=(v:unknown,max=150)=>typeof v==='string'?v.trim().slice(0,max):'';
const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:NaN;
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'});
const valid=(d:string)=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;
const bad=(error:string,status=400)=>Response.json({error},{status});
const joins='SELECT e.*,s.name AS student_name,s.code AS student_code,s.status AS student_status,c.code AS course_code,c.title AS course_title,c.term,c.credits,c.instructor FROM enrollments e JOIN students s ON s.id=e.student_id JOIN courses c ON c.id=e.course_id';
function fail(e:unknown){console.error('School API',e);return bad(e instanceof Error&&e.message.includes('UNIQUE')?'A record with this email, code/term or enrollment already exists.':'The request could not be completed. Please retry.',e instanceof Error&&e.message.includes('UNIQUE')?409:500)}
export async function GET(request:Request){try{const d=db(),q=new URL(request.url).searchParams;if(q.get('studentId')){const id=s(q.get('studentId'),40),student=await d.prepare('SELECT * FROM students WHERE id=?').bind(id).first();if(!student)return bad('Student not found.',404);const [e,a]=await d.batch([d.prepare(joins+' WHERE e.student_id=? ORDER BY c.term,c.code').bind(id),d.prepare('SELECT a.*,c.code AS course_code,c.title AS course_title FROM attendance a JOIN enrollments e ON e.id=a.enrollment_id JOIN courses c ON c.id=e.course_id WHERE e.student_id=? ORDER BY a.day DESC').bind(id)]);return Response.json({student,enrollments:e.results,attendance:a.results})}const [students,courses,enrollments,attendance]=await d.batch([d.prepare('SELECT * FROM students ORDER BY created_at DESC LIMIT 2000'),d.prepare("SELECT c.*,(SELECT COUNT(*) FROM enrollments e WHERE e.course_id=c.id AND e.status='Enrolled') AS enrolled FROM courses c ORDER BY term DESC,code LIMIT 500"),d.prepare(joins+' ORDER BY e.created_at DESC LIMIT 5000'),d.prepare('SELECT a.*,s.name AS student_name,s.code AS student_code,c.code AS course_code,c.title AS course_title,c.term FROM attendance a JOIN enrollments e ON e.id=a.enrollment_id JOIN students s ON s.id=e.student_id JOIN courses c ON c.id=e.course_id ORDER BY a.day DESC LIMIT 10000')]);return Response.json({students:students.results,courses:courses.results,enrollments:enrollments.results,attendance:attendance.results,today:today()})}catch(e){return fail(e)}}
export async function POST(request:Request){let b:Record<string,unknown>;try{b=await request.json() as Record<string,unknown>}catch{return bad('Invalid JSON.')}try{const d=db(),now=new Date().toISOString(),day=today(),id=s(b.id,40);
if(b.action==='student'){const name=s(b.name,100),email=s(b.email,120).toLowerCase(),phone=s(b.phone,30),birth=s(b.birthDate,10),program=s(b.program,80),year=n(b.year),guardian=s(b.guardian,150),address=s(b.address,250);if(!name||!/^\S+@\S+\.\S+$/.test(email)||!valid(birth)||birth>=day||birth<'1900-01-01'||!program||!Number.isInteger(year)||year<1||year>6)return bad('Enter name, email, valid birth date, program and year 1–6.');if(id){const r=await d.prepare('UPDATE students SET name=?,email=?,phone=?,birth_date=?,program=?,year=?,guardian=?,address=? WHERE id=?').bind(name,email,phone,birth,program,year,guardian,address,id).run();if(!r.meta.changes)return bad('Student not found.',404)}else await d.prepare("INSERT INTO students VALUES(?,?,?,?,?,?,?,?,?,?,'Active',?)").bind(crypto.randomUUID(),'ST-'+crypto.randomUUID().slice(0,8).toUpperCase(),name,email,phone,birth,program,year,guardian,address,now).run();return Response.json({message:'Student record saved.'})}
if(b.action==='studentStatus'){const status=s(b.status,20);if(!['Active','Inactive','Graduated'].includes(status))return bad('Invalid student status.');const r=await d.prepare('UPDATE students SET status=? WHERE id=?').bind(status,id).run();return r.meta.changes?Response.json({message:'Student status updated.'}):bad('Student not found.',404)}
if(b.action==='course'){const code=s(b.code,20).toUpperCase(),title=s(b.title,100),instructor=s(b.instructor,80),term=s(b.term,80),schedule=s(b.schedule,100),credits=n(b.credits),capacity=n(b.capacity);if(!code||!title||!instructor||!term||!Number.isInteger(credits)||credits<1||credits>12||!Number.isInteger(capacity)||capacity<1||capacity>500)return bad('Enter course details, credits 1–12 and capacity 1–500.');if(id){const r=await d.prepare("UPDATE courses SET code=?,title=?,instructor=?,term=?,credits=?,capacity=?,schedule=? WHERE id=? AND ?>=(SELECT COUNT(*) FROM enrollments WHERE course_id=? AND status='Enrolled') AND NOT EXISTS(SELECT 1 FROM enrollments WHERE course_id=?)").bind(code,title,instructor,term,credits,capacity,schedule,id,capacity,id,id).run();if(!r.meta.changes)return bad('Course not found or already has enrollment history. Create a new course/term instead.',409)}else await d.prepare("INSERT INTO courses VALUES(?,?,?,?,?,?,?,?,'Open')").bind(crypto.randomUUID(),code,title,instructor,term,credits,capacity,schedule).run();return Response.json({message:'Course saved.'})}
if(b.action==='courseStatus'){const status=s(b.status,20);if(!['Open','Closed'].includes(status))return bad('Invalid course status.');await d.prepare('UPDATE courses SET status=? WHERE id=?').bind(status,id).run();return Response.json({message:'Enrollment availability updated.'})}
if(b.action==='enroll'){const studentId=s(b.studentId,40),courseId=s(b.courseId,40);const r=await d.prepare("INSERT INTO enrollments(id,student_id,course_id,status,score,created_at) SELECT ?,?,?,'Enrolled',NULL,? WHERE EXISTS(SELECT 1 FROM students WHERE id=? AND status='Active') AND EXISTS(SELECT 1 FROM courses c WHERE c.id=? AND c.status='Open' AND (SELECT COUNT(*) FROM enrollments e WHERE e.course_id=c.id AND e.status='Enrolled')<c.capacity)").bind(crypto.randomUUID(),studentId,courseId,now,studentId,courseId).run();return r.meta.changes?Response.json({message:'Student enrolled.'}):bad('Student is inactive, course is closed/full or records are unavailable.',409)}
if(b.action==='withdraw'){const r=await d.prepare("UPDATE enrollments SET status='Withdrawn' WHERE id=? AND status='Enrolled'").bind(id).run();return r.meta.changes?Response.json({message:'Enrollment withdrawn; history retained.'}):bad('Enrollment is unavailable.',409)}
if(b.action==='grade'){const score=b.score===null?null:n(b.score);if(score!==null&&(!Number.isFinite(score)||score<0||score>100))return bad('Grade must be 0–100 or blank.');const r=await d.prepare("UPDATE enrollments SET score=? WHERE id=? AND status='Enrolled'").bind(score,id).run();return r.meta.changes?Response.json({message:'Grade saved.'}):bad('Only current enrollments can be graded.',409)}
if(b.action==='attendance'){const courseId=s(b.courseId,40),date=s(b.day,10),rows=b.rows;if(!valid(date)||date>day||!Array.isArray(rows)||!rows.length||rows.length>500)return bad('Choose a past/today date and at least one attendance mark.');const all=await d.prepare("SELECT e.id FROM enrollments e JOIN students s ON s.id=e.student_id WHERE e.course_id=? AND e.status='Enrolled' AND s.status='Active' AND date(e.created_at,'+8 hours')<=?").bind(courseId,date).all<{id:string}>(),allowed=new Set(all.results.map(x=>x.id)),seen=new Set<string>(),stmts=[];for(const raw of rows){const row=raw as Record<string,unknown>,eid=s(row?.enrollmentId,40),status=s(row?.status,20);if(!allowed.has(eid)||seen.has(eid)||!['Present','Absent','Late','Excused'].includes(status))return bad('Choose valid, distinct current enrollments and attendance marks.');seen.add(eid);stmts.push(d.prepare("INSERT INTO attendance(id,enrollment_id,day,status,updated_at) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM enrollments e JOIN students s ON s.id=e.student_id WHERE e.id=? AND e.status='Enrolled' AND s.status='Active') ON CONFLICT(enrollment_id,day) DO UPDATE SET status=excluded.status,updated_at=excluded.updated_at").bind(crypto.randomUUID(),eid,date,status,now,eid))}await d.batch(stmts);return Response.json({message:'Attendance saved.'})}
if(b.action==='seed'){if(await d.prepare('SELECT id FROM students LIMIT 1').first())return bad('Sample data requires an empty student list.',409);const courses=[{id:crypto.randomUUID(),code:'CS101',title:'Introduction to Computing',instructor:'Prof. Reyes',credits:3,capacity:30,schedule:'Mon / Wed · 8:00–9:30 AM'},{id:crypto.randomUUID(),code:'MATH101',title:'College Mathematics',instructor:'Prof. Santos',credits:3,capacity:35,schedule:'Tue / Thu · 10:00–11:30 AM'},{id:crypto.randomUUID(),code:'ENG101',title:'Academic Communication',instructor:'Prof. Cruz',credits:3,capacity:25,schedule:'Mon / Fri · 1:00–2:30 PM'},{id:crypto.randomUUID(),code:'PE101',title:'Fitness & Wellness',instructor:'Coach Lim',credits:2,capacity:40,schedule:'Friday · 8:00–10:00 AM'}],names=['Alex Rivera','Jamie Santos','Morgan Reyes','Casey Cruz','Sam Garcia','Taylor Lim','Jordan Aquino','Riley Tan','Chris Mendoza','Drew Ramos','Avery Dela Cruz','Pat Flores'],stmts=courses.map(c=>d.prepare("INSERT INTO courses VALUES(?,?,?,?,?,?,?,?,'Open')").bind(c.id,c.code,c.title,c.instructor,'2026–2027 · First semester',c.credits,c.capacity,c.schedule));for(const [i,name] of names.entries()){const sid=crypto.randomUUID(),created=new Date(Date.now()-10*86400000).toISOString();stmts.push(d.prepare("INSERT INTO students VALUES(?,?,?,?,?,?,?,?,?,?,'Active',?)").bind(sid,'ST-2026-'+String(1001+i),name,name.toLowerCase().replaceAll(' ','.')+'@example.com','0917000'+String(1000+i),'2005-04-'+String(10+i),'BS Computer Science',i%3+1,'Guardian '+name.split(' ').at(-1),'Sample address, Manila',created));for(const [j,c] of courses.entries()){if(j===3&&i%2)continue;const eid=crypto.randomUUID();stmts.push(d.prepare("INSERT INTO enrollments VALUES(?,?,?,'Enrolled',?,?)").bind(eid,sid,c.id,i%4===0?null:70+(i*3+j)%29,created));for(let k=0;k<3;k++){const date=new Date(Date.parse(day)-(k+1)*86400000).toISOString().slice(0,10);stmts.push(d.prepare('INSERT INTO attendance VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),eid,date,(i+j+k)%7===0?'Absent':(i+j)%5===0?'Late':'Present',now))}}}await d.batch(stmts);return Response.json({message:'Sample campus loaded.'})}
return bad('Unknown action.');}catch(e){return fail(e)}}
